### PR TITLE
Environment variables support added

### LINKED ISSUE #116: Support for native environment variables
AWS lambda supports now native environment variables: http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html

### PR DESCRIPTION
**Pull request by tdi**
Closes #116 

You can add to the settings.yml:
```
environement:
  Varname: something
  varnam033sjks_s: "something else"
```

### CODE REVIEW

**Comment by zivbaz** [comment]
Any idea when this PR is going to be merged?

**Comment by kpiotrowski** [comment]
:+1:

**Comment by tdi** [comment]
@jorgebastida any ETA on accepting this one?

**Comment by ericblade** [comment]
hi @tdi  .. it looks like @jorgebastida has disappeared for a little while.. I've made a fork of this repo, and am interested in this.  I'm wondering if there's any way to specify a different variable value, based on other values that are known at the time of running gordon?  some way to set like "if stage is PROD then SERVERHOST=productionserver.host.com; else SERVERHOST=developserver.host.com".  Any idea how one would go about doing that?  If that's not already possible, is that something you'd find interesting?

**Comment by jorgebastida** [comment]
Thank you very much @tdi  - Will try to be more responsive in the future :)

**Comment by ZivRechnitser** [comment]
@tdi @jorgebastida any option to add the ability to use parameters:
VARIABLE: ref://parameter?

**Pull request merged**
