### PR TITLE
Fix zip filename encoding & switch to ZIP_DEFLATED

### PR DESCRIPTION
**Pull request by ninjabear**

### CODE REVIEW

**Comment by ninjabear** [comment]
Closes #94 and #61

**Comment by alexanderdean** [comment]
Hey @ninjabear - is this WIP or ready for review by @jorgebastida ?

**Comment by ninjabear** [comment]
Whoops! I was sure I changed that title. Yes it is ready for review - apologies for the confusion

**Comment by alexanderdean** [comment]
Hey @jorgebastida - any thoughts on when this might be merged? This is the last dependency on our [Kinesis Tee](https://github.com/snowplow/kinesis-tee) release.

**Comment by ninjabear** [comment]
Hi @jorgebastida! I'm guessing you're a bit pushed for time - is there anything I can do to help this PR along?

**Comment by jorgebastida** [comment]
Thank you very much this! had no idea you where implementing tee using gordon! 👍

**Comment by alexanderdean** [comment]
Thank *you* @jorgebastida!

Yes, we love Gordon. We're going to port this other project over in due course too: https://github.com/snowplow/snowplow-aws-lambda-source/issues/3

**Pull request merged**
