### PR TITLE
Add support for python3.6 runtime

### LINKED ISSUE #146: Add python3.6 runtime
~~~
    _default_runtime = 'python2.7'
    _runtimes = {
        'python': 'python2.7',
        'python2.7': 'python2.7',
        'python2': 'python2.7'
    }
~~~

Seems to be missing [python3.6](http://docs.aws.amazon.com/lambda/latest/dg/python-programming-model-handler-types.html) (and `python3` alias)

### PR DESCRIPTION
**Pull request by candlerb**
Fixes #146

### CODE REVIEW

**Comment by SakuraSound** [comment]
Would love to see this get merged!

**Comment by jakul** [comment]
@jorgebastida What needs to be done to get this PR merged?

**Comment by ticosax** [comment]
It could be reflected on the documentation as well.

**Comment by candlerb** [comment]
/me too impatient, have switched to serverless and it's working very well for me

**Comment by jorgebastida** [comment]
Thank for the patch @candlerb . Will release this as part of ``0.7.0``

**Pull request merged**
