### PR TITLE
Update example README to reflect S3 naming restrictions

### PR DESCRIPTION
**Pull request by ausmith**
I believe this will tackle the documentation gap mentioned in #9. Let me know if I missed any other documentation opportunities in the repo as I have not familiarized myself with all of it yet.

### CODE REVIEW

**Comment by ausmith** [comment]
It looks like `code-bucket` is utilized in multiple places throughout the examples. Is there a better place to document this at a more global place in the documentation?

**Comment by jorgebastida** [comment]
Hello @ausmith yes... I think that is quite a good comment to add to the main readme of the examples directory https://github.com/jorgebastida/gordon/blob/master/examples/README.md All sample projects define a bucket which will probably exist if people try to apply the example without changing it.

I'll think for a better solution ... but atm adding that piece of documentation to the README of the examples directory is the best idea.

**Comment by ausmith** [comment]
Perfect, I'll make the change here.

**Comment by ausmith** [comment]
@jorgebastida how's that?

**Pull request merged**
